site_name: waku
site_author: Krau
site_description: Tài liệu triển khai, cấu hình và sử dụng waku
repo_name: TakeshiBot/waku-bot
repo_url: https://github.com/TakeshiBot/waku-bot
copyright: CC BY-NC-SA 4.0
theme:
  name: material
  language: vi
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Đổi giao diện
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Giao diện tối
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Giao diện sáng

nav:
  - index.md
  - help.md
  - self-host.md
  - webapp.md
  - discord.md
  - i18n.md
  - branding-timezone.md
  - license.md
